apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx2
  namespace: default
  labels:
    app:  nginx2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nginx2
    spec:
      containers:
      - name:  nginx2
        image: localhost:5000/python:1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
      restartPolicy: Always